Update Go and Rosetta SDK versions
Zondax/rosetta-filecoin-proxy pull request #151
Opened 2022-02-02 13:10 UTC by Anonyma

2022-02-02 20:10 UTC, jleni requested changes
You need to upgrade go version in circleci too

this is one of the places (there are others in the same file)
https://github.com/Zondax/rosetta-filecoin-proxy/blob/07cec4da7e261672089d78ab3c7e0a855f4d58f1/.circleci/config.yml#L34

2022-02-07 13:00 UTC, raynaudoe approved these changes

2022-02-07 19:28 UTC, jleni approved these changes

2022-02-08 08:22 UTC, jleni commented
<img width="689" alt="image" src="https://user-images.githubusercontent.com/13698520/152946650-5925e7db-4bb7-419b-80c9-2cf640c642e0.png">

2022-02-08 08:22 UTC, jleni approved these changes

2022-02-08 08:23 UTC, merged